### ISSUE TITLE
How to load files

### ISSUE THREAD

**Issue by timo-cmd** [ftchirou/blink#1]
Hello dear, 

How can somebody load files in the repl? Could you explain a little bit more precisle?
I follow you and wish you success. 

Thanks and regards.

Timo

**Comment by Link-Byte** [comment]
I'm not a maintainer of this repository, but to load files you simply type `:load filename.extension` in the REPL. The file should be imported into the current environment and you should be able to access defined classes from the REPL :)

**Comment by timo-cmd** [comment]
Thanks, but when I load for example the guessnumber sample into the repl, how do I can start the game?

Sorry for my dumbness but I’m right now really lost.

Thanks and regards
Timo

**Comment by Link-Byte** [comment]
you simply load the file and once the REPL says that the class `GuessNumber` is defined, you just do `new GuessNumber().play()` and you're set :)

**Comment by timo-cmd** [comment]
Thanks bro👊🏻
